### ISSUE TITLE
[python / documentation] documentation is no more taking 100% with sphinx >= 5.0.0

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#665]
With sphinx >= 5.0.0, in generated `sphinx/_static/classic.css` file, one can see:
```css
div.document {
    display: flex;
    background-color: white;
}
```

which leads to the same issue than [this python-docs-theme issue](https://github.com/python/python-docs-theme/issues/92).

If one removes the line `display: flex;`, the text takes 100% of the web page.
